#!/usr/bin/python
ncars=100
npass=85
ndrivers=30
ncars_left=ncars-ndrivers
print(ncars_left)
ncars_used=(ncars-ncars_left)
print(ncars_used)
transported=(ndrivers+npass)
print(transported)
avg_pass=(npass/ndrivers)
print(avg_pass)
